In [1]:
import numpy as np

In [ ]:
""" return array object """
ones_arr = np.array([[[1,1,1,1],[1,1,1,1],[1,1,1,1]],[[1,1,1,1],[1,1,1,1],[1,1,1,1]]])
print(ones_arr)

In [2]:
""" return array object """
zero_arr = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(zero_arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## reshape function : reshape dimension of array with given dimension

In [ ]:
reshape_arr = zero_arr.reshape(4,3)
print(reshape_arr)

## arange function : return arr obj from range low to high with step and data type

In [3]:
arange_arr = np.arange(10,31,1,dtype=int)
print(arange_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


## reverse array with slicing [start:stop:step], only step is given negative so it start from end

In [ ]:
arr = np.array([1,2,3,4,5])
new_arr = arr[::-1]
new_arr

## transpose function : return array object with row and column swapped

In [4]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## flatten function : return array object with all dimension flatten to 1D

In [ ]:
arr = np.arange(1,10).reshape(3,3)
new_arr = arr.flatten()
new_arr

## Add two Arrays

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)

sum = arr1 + arr2

print(sum)

## matmul function : return array object with matrix multiplication of two array

In [5]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(11,13).reshape(2,1)

print(np.matmul(arr1, arr2))

[[35]
 [81]]


## Mean, Median and Standard Deviation of array object
> Mean: sum of a collection of numbers divided by the count of numbers in the collection <br>
Median: the middle value of the given list of data when arranged in an order <br>
Standard Deviation: measure of the amount of variation of a random variable expected about its mean. A low standard deviation indicates that the values tend to be close to the mean of the set, while a high standard deviation indicates that the values are spread out over a wider range

In [7]:
arr = np.arange(1,10).reshape(3,3)
print("mean: ",np.mean(arr))
print("median: ",np.median(arr))
print("standard deviation: ",np.std(arr))

mean:  5.0
median:  5.0
standard deviation:  2.581988897471611


## Indexing

In [8]:
arr = np.arange(1,10,1,dtype=int)
matrix = arr.reshape(3,3)
print(matrix)
print(matrix[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


## Slicing

In [9]:
arr = np.arange(1,17,1,dtype=int)
matrix = arr.reshape(4,4)
print(matrix)
print()
new_arr = matrix[0:2, 2:4]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[3 4]
 [7 8]]


## Even number filtering 

In [ ]:
arr = np.arange(0,11,2)
print(arr)

 ## Broadcasting
 > Broadcasting: this term describe how numpy treat array with different size at airthmetic operations. Smaller array is broadcast across large array
    - If array is not matched in size, numpy will broadcast the smaller array to the larger array size
    - Broadcasting is possible if the smaller array can be broadcast to the larger array size

In [5]:
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])


## broadcast happend because array size is not matched
"""
[[1][2][3]       [4 4 4]        [[5 6 7]
[1][2][3]    +   [5 5 5]  --->  [6 7 8]
[1][2][3]]      [6 6 6]         [7 8 9]]
"""
print(x+y)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [9]:
const = 3
arr = np.arange(1,10).reshape(3,3)

"""broadcasting happend because of mismatch in array dimension """
print(3+arr)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
x = np.arange(1,4).reshape(3,1)
y = np.arange(1,4).reshape(1,3)

"""broadcasting happend because of mismatch in array dimension """
print(x+y)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

## Dot product of two array

In [10]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,13).reshape(4,3)
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

## Determinant of given array

In [11]:
a = np.random.randint(1,10,9).reshape(3,3)

print(np.linalg.det(a))

-131.99999999999997


## System of linear equations represented by matrices.

In [12]:
a = np.array([[2,4,6], [4,5,6], [3,1,-2]])
b = np.array([18,24,4])
x = np.linalg.solve(a,b)
x

array([ 4., -2.,  3.])

## Generate random value for matrix

In [14]:
np.random.randint(1,10,9,dtype=int).reshape(3,3)

array([[7, 9, 8],
       [4, 2, 5],
       [3, 2, 7]])

## Standard normal distribution
>  also called the z-distribution, is a special normal distribution where the mean is 0 and the standard deviation is 1
### standard_normal function : is a function provided by random to give standard nrml of random values

In [13]:
0 + 1 * np.random.standard_normal(size=(2,2))

array([[-0.67310141, -1.67445832],
       [-2.0614567 , -0.43260207]])

## Stack matrix horizontally and vertically
> stack method: Join a sequence of arrays along a new axis.

In [15]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr = np.stack((arr1,arr2))
print(arr)
array = np.stack((arr1,arr2),axis=-1)
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## Split arrays in equal parts
> split method: Split an array into multiple sub-arrays as views into ary.

In [16]:
arr = np.arange(1,17).reshape(4,4)

print(np.split(arr, 4))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


## MAX MIN MEAN SUM 

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
max = np.max(arr)
print("max: ",max)
min = np.min(arr)
print("min: ",min)
mean = np.mean(arr)
print("mean: ",mean)
sum = np.sum(arr)
print("sum: ",sum)

max:  10
min:  1
mean:  5.5
sum:  55


## Cumulative sum

In [18]:
arr = np.arange(1,10).reshape(3,3)
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

## correlation Coefficient

In [19]:
a = np.random.randint(1,10,10,dtype=int)
b = np.random.randint(1,10,10,dtype=int)

np.corrcoef(a,b)

array([[1.        , 0.01715996],
       [0.01715996, 1.        ]])

## Elements checking using compare operators

In [20]:
a = np.random.randint(1,10,10,dtype=int)
b = np.random.randint(1,10,10,dtype=int)

print(a<b)
print(a>b)
print(a==b)

[False  True  True False  True  True False False False  True]
[ True False False  True False False False  True  True False]
[False False False False False False  True False False False]


In [21]:
a = np.random.randint(1,10,10)

print(a[a<5])

[1 4 1]
